name: Auto Assign Issues to Project

on:
  issues:
    types: [opened]
    
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  auto_assign_issues:
    runs-on: ubuntu-latest
    name: Auto-assign new issues to projects
    steps:
    - run: echo "${{github.event.issue.title}}"

    - name: Assign Bugs to the Bug Tracker
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened' && startsWith(github.event.issue.title, '🐛 BUG:')
      with:
        project: 'https://github.com/PraiseCharts/ChordChartJS/projects/3'
        column_name: 'Needs Triage'

    - name: Assign RFCs to the RFC Tracker
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened' && startsWith(github.event.issue.title, '💡 RFC:')
      with:
        project: 'https://github.com/PraiseCharts/ChordChartJS/projects/2'
        column_name: 'Discussing'
